Adds a toggle to allow shape files with no dbf
phpmyadmin/shapefile pull request #38
Opened 2024-11-08 08:57 UTC by JoolsMcFly

Hi.

This PR fixes #36 as it gives users the ability to process a shape file with no matching dbf file.
A call to `$shp->setAllowNoDbf(true);` does the trick.

When running `composer test` I had several warnings from `phpcbf` so I fixed those as well.

Thanks for reviewing.

2024-11-15 09:43 UTC, JoolsMcFly commented
Hi @MauricioFauth .

Bumping this to wonder what you think?

2024-11-16 08:27 UTC, williamdes commented on data/no-dbf.shp
Can you let us know how you generated this file
as you know recently there was a big incident at xz with data test files

2024-11-16 16:30 UTC, MauricioFauth requested changes
Could you target the 3.1.x branch?

2024-11-16 16:30 UTC, MauricioFauth commented on data/no-dbf.shp
Why this file had to be changed?

2024-11-16 17:11 UTC, liviuconcioiu commented on data/no-dbf.shp
@williamdes I don't think it was generated, but copied from somewhere else. I do see this file signature goes back to 2022. https://www.virustotal.com/gui/file/0249c1f84a8394f24dccf5db8fdc8fbe6663b5f3c1b686f3a162288590d18c66

2024-11-17 18:26 UTC, JoolsMcFly commented on data/no-dbf.shp
Hi guys.

`no-dbf.shp` was there before I opened my PR but it was just an empty file ([file on master](https://github.com/phpmyadmin/shapefile/blob/master/data/no-dbf.shp)).

My PR allows opening a file with no dbf but since `no-dbf-shp` was empty I had another error because code was complaining, rightfully so, that `no-dbf.shp` was not a valid shapefile (no headers to be found).
To remedy that I just duplicated `mexico.shp` and renamed it `no-dbf.shp`.

2024-11-17 18:29 UTC, JoolsMcFly commented
> Could you target the 3.1.x branch?

Sure. I edited my PR and made it target 3.1.x branch.

2024-11-19 15:02 UTC, MauricioFauth commented
> Wouldn't it be easier to open a new PR from a branch off 3.1.x?

You can do something like this in the branch of this PR:
```
git reset --hard upstream/3.1.x
git cherry-pick -s COMMIT_HASH
```

`COMMIT_HASH` in this case is `c75ab1506dbebfcd045cdbd54be73187e8d3c226` and `upstream` is the remote name for `git@github.com:phpmyadmin/shapefile.git`

2024-11-19 22:08 UTC, JoolsMcFly commented
I opened another PR targeting 3.1.x because I couldn't just cherry-pick, more changes were needed.
So I think you can remove the 3.1.10 milestone from here and add it to the other PR.

What do you think?

2024-11-29 10:23 UTC, JoolsMcFly commented
Lil bump to know what you guys think?

Thanks!

2024-12-08 17:09 UTC, closed without merging